set_property SRC_FILE_INFO {cfile:C:/Users/baolin/Desktop/MyProjects/zynq_prj/HelloWorld/HelloWorld.srcs/constrs_1/new/pin.xdc rfile:../../../HelloWorld.srcs/constrs_1/new/pin.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V13 [get_ports {GPIO_0_0_tri_io[2]}]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V14 [get_ports {GPIO_0_0_tri_io[1]}]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V15 [get_ports {GPIO_0_0_tri_io[0]}]
